version: '3.7'

services:

  liqpay:
    build:
      dockerfile: Dockerfile
      context: ./
#    uncomment next lines to change service port
#    environment:
#      PORT: 5000
#    expose:
#      - 5000
